<?php
/**
 * Mostly globals
 *
 * @package Colby/Counselors
 */

global $FIELD_GROUP;
global $INTL_TERRITORIES;
global $US_TERRITORIES;

$FIELD_GROUP = [
'id' => 'acf_counselor-fields',
	'title' => 'Counselor Fields',
	'fields' => [
		[
			'key' => 'field_54184c182fc22',
			'label' => 'Locations',
			'name' => 'locations',
			'type' => 'select',
			'required' => 0,
			'choices' => [
				'Alabama' => 'Alabama',
				'Alaska' => 'Alaska',
				'Arizona' => 'Arizona',
				'Arkansas' => 'Arkansas',
				'California' => 'California',
				'California (Northern)' => 'California (Northern)',
				'California (Southern)' => 'California (Southern)',
				'Colorado' => 'Colorado',
				'Connecticut' => 'Connecticut',
				'Delaware' => 'Delaware',
				'District of Columbia' => 'District of Columbia',
				'Florida' => 'Florida',
				'Georgia' => 'Georgia',
				'Hawaii' => 'Hawaii',
				'Idaho' => 'Idaho',
				'Illinois' => 'Illinois',
				'Indiana' => 'Indiana',
				'Iowa' => 'Iowa',
				'Kansas' => 'Kansas',
				'Kentucky' => 'Kentucky',
				'Louisiana' => 'Louisiana',
				'Maine' => 'Maine',
				'Maine (Central)' => 'Maine (Central)',
				'Maine (Northern)' => 'Maine (Northern)',
				'Maine (Southern)' => 'Maine (Southern)',
				'Maryland' => 'Maryland',
				'Massachusetts' => 'Massachusetts',
				'Massachusetts (Boston area)' => 'Massachusetts (Boston area)',
				'Massachusetts (Boston, Cambridge)' => 'Massachusetts (Boston, Cambridge)',
				'Massachusetts (Central)' => 'Massachusetts (Central)',
				'Massachusetts (Cape Cod)' => 'Massachusetts (Cape Cod)',
				'Massachusetts (Essex County)' => 'Massachusetts (Essex County)',
				'Massachusetts (Essex County, South Shore)' => 'Massachusetts (Essex County, South Shore)',
				'Massachusetts (Lowell, Concord, Wellesley, Milton, Lexington, Waltham)' => 'Massachusetts (Lowell, Concord, Wellesley, Milton, Lexington, Waltham)',
				'Massachusetts (Western)' => 'Massachusetts (Western)',
				'Michigan' => 'Michigan',
				'Minnesota' => 'Minnesota',
				'Mississippi' => 'Mississippi',
				'Missouri' => 'Missouri',
				'Montana' => 'Montana',
				'Nebraska' => 'Nebraska',
				'Nevada' => 'Nevada',
				'New Hampshire' => 'New Hampshire',
				'New Jersey' => 'New Jersey',
				'New Mexico' => 'New Mexico',
				'New York' => 'New York',
				'New York City' => 'New York City',
				'New York (Manhattan)' => 'New York (Manhattan)',
				'New York (Long Island)' => 'New York (Long Island)',
				'New York (except Manhattan and Long Island)' => 'New York (except Manhattan and Long Island)',
				'New York (Upstate)' => 'New York (Upstate)',
				'New York (Westchester)' => 'New York (Westchester)',
				'North Carolina' => 'North Carolina',
				'North Dakota' => 'North Dakota',
				'Ohio' => 'Ohio',
				'Oklahoma' => 'Oklahoma',
				'Oregon' => 'Oregon',
				'Pennsylvania' => 'Pennsylvania',
				'Rhode Island' => 'Rhode Island',
				'South Carolina' => 'South Carolina',
				'South Dakota' => 'South Dakota',
				'Tennessee' => 'Tennessee',
				'Texas' => 'Texas',
				'Utah' => 'Utah',
				'Vermont' => 'Vermont',
				'Virginia' => 'Virginia',
				'Washington' => 'Washington',
				'West Virginia' => 'West Virginia',
				'Wisconsin' => 'Wisconsin',
				'Wyoming' => 'Wyoming',
				'Africa' => 'Africa',
				'Bermuda' => 'Bermuda',
				'Canada' => 'Canada',
				'Caribbean' => 'Caribbean',
                                'China' => 'China',
				'East Asia' => 'East Asia',
				'Eurasia' => 'Eurasia',
				'Europe' => 'Europe',
				'Greater Indian Subcontinent' => 'Greater Indian Subcontinent',
				'Latin America' => 'Latin America',
				'Mexico' => 'Mexico',
				'Middle East' => 'Middle East',
				'Oceania' => 'Oceania',
				'Southeast Asia' => 'Southeast Asia',
				],
			'default_value' => '',
			'allow_null' => 0,
			'multiple' => 1,
		],
		[
			'key' => 'field_x4185a4f2c415',
			'label' => 'Job Title',
			'name' => 'jobtitle',
			'type' => 'text',
			'required' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		],
		[
			'key' => 'field_54185a4f2c415',
			'label' => 'Phone',
			'name' => 'phone',
			'type' => 'text',
			'required' => 1,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		],
		[
			'key' => 'field_54185a7a2c416',
			'label' => 'Email',
			'name' => 'email',
			'type' => 'email',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		],
		[
			'key' => 'field_545c292214b26',
			'label' => 'Regional Representative',
			'name' => 'regional_representative',
			'prefix' => '',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'choices' => [
				'yes' => 'Yes',
				],
			'default_value' => array(),
			'layout' => 'vertical',
		],
	],
	'location' => [
		[
			[
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'counselors',
				'order_no' => 0,
				'group_no' => 0,
			],
		],
	],
	'options' => [
		'position' => 'normal',
		'layout' => 'no_box',
		'hide_on_screen' => [],
		],
	'menu_order' => 0,
];


$US_TERRITORIES = [
	'Alabama',
	'Alaska',
	'Arizona',
	'Arkansas',
	'California (Northern)',
	'California (Southern)',
	'Colorado',
	'Connecticut',
	'Delaware',
	'District of Columbia',
	'Florida',
	'Georgia',
	'Hawaii',
	'Idaho',
	'Illinois',
	'Indiana',
	'Iowa',
	'Kansas',
	'Kentucky',
	'Louisiana',
	'Maine (Central)',
	'Maine (Northern)',
	'Maine (Southern)',
	'Maryland',
	'Massachusetts (Boston, Cambridge)',
	'Massachusetts (Central)',
	'Massachusetts (Cape Cod)',
	'Massachusetts (Essex County, South Shore)',
	'Massachusetts (Lowell, Concord, Wellesley, Milton, Lexington, Waltham)',
	'Massachusetts (Western)',
	'Michigan',
	'Minnesota',
	'Mississippi',
	'Missouri',
	'Montana',
	'Nebraska',
	'Nevada',
	'New Hampshire',
	'New Jersey',
	'New Mexico',
	'New York (Long Island)',
	'New York (Upstate)',
	'New York (Westchester)',
	'New York City',
	'North Carolina',
	'North Dakota',
	'Ohio',
	'Oklahoma',
	'Oregon',
	'Pennsylvania',
	'Rhode Island',
	'South Carolina',
	'South Dakota',
	'Tennessee',
	'Texas',
	'Vermont',
	'Virginia',
	'Washington',
	'West Virginia',
	'Wisconsin',
	'Wyoming',
];

$INTL_TERRITORIES = [
	'Africa',
	'Bermuda',
	'Canada',
	'Caribbean',
        'China',
	'East Asia',
	'Eurasia',
	'Europe',
	'Greater Indian Subcontinent',
	'Latin America',
	'Mexico',
	'Middle East',
	'Oceania',
	'Southeast Asia',
];
