<?php

if ( ! function_exists( 'register_field_group' ) ) {
    return;
}

register_field_group( [
'id' => 'acf_counselor-fields',
	'title' => 'Counselor Fields',
	'fields' => [
		[
			'key' => 'field_54184c182fc22',
			'label' => 'Locations',
			'name' => 'locations',
			'type' => 'select',
			'required' => 0,
			'choices' => [
				'Alabama' => 'Alabama',
				'Alaska' => 'Alaska',
				'Arizona' => 'Arizona',
				'Arkansas' => 'Arkansas',
				'California' => 'California',
				'California (Northern)' => 'California (Northern)',
				'California (Southern)' => 'California (Southern)',
				'Colorado' => 'Colorado',
				'Connecticut' => 'Connecticut',
				'Delaware' => 'Delaware',
				'District of Columbia' => 'District of Columbia',
				'Florida' => 'Florida',
				'Georgia' => 'Georgia',
				'Hawaii' => 'Hawaii',
				'Idaho' => 'Idaho',
				'Illinois' => 'Illinois',
				'Indiana' => 'Indiana',
				'Iowa' => 'Iowa',
				'Kansas' => 'Kansas',
				'Kentucky' => 'Kentucky',
				'Louisiana' => 'Louisiana',
				'Maine' => 'Maine',
				'Maine (Central)' => 'Maine (Central)',
				'Maine (Northern)' => 'Maine (Northern)',
				'Maine (Southern)' => 'Maine (Southern)',
				'Maryland' => 'Maryland',
				'Massachusetts' => 'Massachusetts',
				'Massachusetts (Boston area)' => 'Massachusetts (Boston area)',
				'Massachusetts (Boston, Cambridge)' => 'Massachusetts (Boston, Cambridge)',
				'Massachusetts (Central)' => 'Massachusetts (Central)',
                'Massachusetts (Central, Cape Cod, and Islands)' => 'Massachusetts (Central, Cape Cod, and Islands)',
				'Massachusetts (Essex County)' => 'Massachusetts (Essex County)',
				'Massachusetts (Essex, Norfolk, Bristol, and Plymouth Counties)' => 'Massachusetts (Essex, Norfolk, Bristol, and Plymouth Counties)',
				'Massachusetts (Lowell, Concord, Wellesley, Milton, Lexington, Waltham)' => 'Massachusetts (Lowell, Concord, Wellesley, Milton, Lexington, Waltham)',
				'Massachusetts (Western)' => 'Massachusetts (Western)',
				'Michigan' => 'Michigan',
				'Minnesota' => 'Minnesota',
				'Mississippi' => 'Mississippi',
				'Missouri' => 'Missouri',
				'Montana' => 'Montana',
				'Nebraska' => 'Nebraska',
				'Nevada' => 'Nevada',
				'New Hampshire' => 'New Hampshire',
				'New Jersey' => 'New Jersey',
				'New Mexico' => 'New Mexico',
				'New York' => 'New York',
				'New York (Manhattan)' => 'New York (Manhattan)',
				'New York (except Westchester and Manhattan)' => 'New York (except Westchester and Manhattan)',
				'New York (Westchester)' => 'New York (Westchester)',
				'North Carolina' => 'North Carolina',
				'North Dakota' => 'North Dakota',
				'Ohio' => 'Ohio',
				'Oklahoma' => 'Oklahoma',
				'Oregon' => 'Oregon',
				'Pennsylvania' => 'Pennsylvania',
				'Rhode Island' => 'Rhode Island',
				'South Carolina' => 'South Carolina',
				'South Dakota' => 'South Dakota',
				'Tennessee' => 'Tennessee',
				'Texas' => 'Texas',
				'Utah' => 'Utah',
				'Vermont' => 'Vermont',
				'Virginia' => 'Virginia',
				'Washington' => 'Washington',
				'West Virginia' => 'West Virginia',
				'Wisconsin' => 'Wisconsin',
				'Wyoming' => 'Wyoming',
				'Africa' => 'Africa',
				'Bermuda' => 'Bermuda',
				'Canada' => 'Canada',
				'Caribbean' => 'Caribbean',
				'East Asia' => 'East Asia',
                'East and Southeast Asia' => 'East and Southeast Asia',
				'Eurasia' => 'Eurasia',
				'Europe' => 'Europe',
				'Greater Indian Subcontinent' => 'Greater Indian Subcontinent',
				'Latin America' => 'Latin America',
				'Mexico' => 'Mexico',
				'Middle East' => 'Middle East',
				'Oceania' => 'Oceania',
				],
			'default_value' => '',
			'allow_null' => 0,
			'multiple' => 1,
		],
		[
			'key' => 'field_x4185a4f2c415',
			'label' => 'Job Title',
			'name' => 'jobtitle',
			'type' => 'text',
			'required' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		],
		[
			'key' => 'field_54185a4f2c415',
			'label' => 'Phone',
			'name' => 'phone',
			'type' => 'text',
			'required' => 1,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
		],
		[
			'key' => 'field_54185a7a2c416',
			'label' => 'Email',
			'name' => 'email',
			'type' => 'email',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		],
		[
			'key' => 'field_545c292214b26',
			'label' => 'Regional Representative',
			'name' => 'regional_representative',
			'prefix' => '',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'choices' => [
				'yes' => 'Yes',
				],
			'default_value' => array(),
			'layout' => 'vertical',
		],
	],
	'location' => [
		[
			[
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'counselors',
				'order_no' => 0,
				'group_no' => 0,
			],
		],
	],
	'options' => [
		'position' => 'normal',
		'layout' => 'no_box',
		'hide_on_screen' => [],
		],
	'menu_order' => 0,
] );
