var simplemaps_usmap_mapdata = {
	main_settings: {
		//General settings
		width: 'responsive', //or 'responsive'
		background_color: '#FFFFFF',
		background_transparent: 'yes',
		popups: 'detect',

		//State defaults
		state_description: 'State description',
		state_color: '#3973b8',
		state_hover_color: '#9EA9B0',
		state_url: 'https://simplemaps.com',
		border_size: 1.5,
		border_color: '#ffffff',
		all_states_inactive: 'no',
		all_states_zoomable: 'no',

		//Location defaults
		location_description: 'Location description',
		location_color: '#FF0067',
		location_opacity: 0.8,
		location_hover_opacity: 1,
		location_url: '',
		location_size: 25,
		location_type: 'square',
		location_border_color: '#FFFFFF',
		location_border: 2,
		location_hover_border: 2.5,
		all_locations_inactive: 'no',
		all_locations_hidden: 'no',

		//Label defaults
		label_color: '#ffffff',
		label_hover_color: '#ffffff',
		label_size: 22,
		label_font: 'Arial',
		hide_labels: 'no',

		//Zoom settings
		manual_zoom: 'no',
		back_image: 'no',
		arrow_box: 'no',
		navigation_size: '40',
		navigation_color: '#f7f7f7',
		navigation_border_color: '#636363',
		initial_back: 'no',
		initial_zoom: -1,
		initial_zoom_solo: 'no',
		region_opacity: 1,
		region_hover_opacity: 0.6,
		zoom_out_incrementally: 'yes',
		zoom_percentage: 0.99,
		zoom_time: 0.5,

		//Popup settings
		popup_color: 'white',
		popup_opacity: 0.9,
		popup_shadow: 1,
		popup_corners: 5,
		popup_font: '12px/1.5 Verdana, Arial, Helvetica, sans-serif',
		popup_nocss: 'no',

		//Advanced settings
		div: 'map1',
		auto_load: 'yes',
		rotate: '0',
		url_new_tab: 'no',
		images_directory: 'default',
		import_labels: 'no',
		fade_time: 0.1,
		link_text: 'View Website',
	},
	state_specific: {
		HI: {
			name: 'Hawaii',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'HI', slug: 'hawaii' })",
		},
		AK: {
			name: 'Alaska',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'AK', slug: 'alaska' })",
		},
		FL: {
			name: 'Florida',
			description: 'fdsafdsa fdsa fdsa fdsa fdsafdsafdsafdfdsa',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'FL', slug: 'florida' })",
		},
		NH: {
			name: 'New Hampshire',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'NH', slug: 'new-hampshire' })",
		},
		VT: {
			name: 'Vermont',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'VT', slug: 'vermont' })",
		},
		ME: {
			name: 'Maine',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'ME', slug: 'maine' })",
		},
		RI: {
			name: 'Rhode Island',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'RI', slug: 'rhode-island' })",
		},
		NY: {
			name: 'New York',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'NY', slug: 'new-york' })",
		},
		PA: {
			name: 'Pennsylvania',
			description: 'default',
			color: 'default',
			url: "javascript:clickState({ abbreviation: 'PA', slug: 'pennsylvania' })",
		},
		NJ: {
			name: 'New Jersey',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'NJ', slug: 'new-jersey' })",
		},
		DE: {
			name: 'Delaware',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'DE', slug: 'delaware' })",
		},
		MD: {
			name: 'Maryland',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'MD', slug: 'maryland' })",
		},
		VA: {
			name: 'Virginia',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'VA', slug: 'virginia' })",
		},
		WV: {
			name: 'West Virginia',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'WV', slug: 'west-virginia' })",
		},
		OH: {
			name: 'Ohio',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'OH', slug: 'ohio' })",
		},
		IN: {
			name: 'Indiana',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'IN', slug: 'indiana' })",
		},
		IL: {
			name: 'Illinois',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'IL', slug: 'illinois' })",
		},
		CT: {
			name: 'Connecticut',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'CT', slug: 'connecticut' })",
		},
		WI: {
			name: 'Wisconsin',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'WI', slug: 'wisconsin' })",
		},
		NC: {
			name: 'North Carolina',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'NC', slug: 'north-carolina' })",
		},
		DC: {
			name: 'District of Columbia',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'DC', slug: 'sictrict-of-columbia' })",
		},
		MA: {
			name: 'Massachusetts',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'MA', slug: 'massachusetts' })",
		},
		TN: {
			name: 'Tennessee',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'TN', slug: 'tennessee' })",
		},
		AR: {
			name: 'Arkansas',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'AR', slug: 'arkansas' })",
		},
		MO: {
			name: 'Missouri',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'MO', slug: 'missouri' })",
		},
		GA: {
			name: 'Georgia',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'GA', slug: 'georgia' })",
		},
		SC: {
			name: 'South Carolina',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'SC', slug: 'south-carolina' })",
		},
		KY: {
			name: 'Kentucky',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'KY', slug: 'kentucky' })",
		},
		AL: {
			name: 'Alabama',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'AL', slug: 'alabama' })",
		},
		LA: {
			name: 'Louisiana',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'LA', slug: 'louisiana' })",
		},
		MS: {
			name: 'Mississippi',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'MS', slug: 'mississippi' })",
		},
		IA: {
			name: 'Iowa',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'IA', slug: 'iowa' })",
		},
		MN: {
			name: 'Minnesota',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'MN', slug: 'minnesota' })",
		},
		OK: {
			name: 'Oklahoma',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'OK', slug: 'oklahoma' })",
		},
		TX: {
			name: 'Texas',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'TX', slug: 'texas' })",
		},
		NM: {
			name: 'New Mexico',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'NM', slug: 'new-mexico' })",
		},
		KS: {
			name: 'Kansas',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'KS', slug: 'kansas' })",
		},
		NE: {
			name: 'Nebraska',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'NE', slug: 'nebraska' })",
		},
		SD: {
			name: 'South Dakota',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'SD', slug: 'south-dakota' })",
		},
		ND: {
			name: 'North Dakota',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'ND', slug: 'north-dakota' })",
		},
		WY: {
			name: 'Wyoming',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'WY', slug: 'wyoming' })",
		},
		MT: {
			name: 'Montana',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'MT', slug: 'montana' })",
		},
		CO: {
			name: 'Colorado',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'CO', slug: 'colorado' })",
		},
		UT: {
			name: 'Utah',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'UT', slug: 'utah' })",
		},
		AZ: {
			name: 'Arizona',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'AZ', slug: 'arizona' })",
		},
		NV: {
			name: 'Nevada',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'NV', slug: 'nevada' })",
		},
		OR: {
			name: 'Oregon',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'OR', slug: 'oregon' })",
		},
		WA: {
			name: 'Washington',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'WA', slug: 'washington' })",
		},
		CA: {
			name: 'California',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'CA', slug: 'california' })",
		},
		MI: {
			name: 'Michigan',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'MI', slug: 'michigan' })",
		},
		ID: {
			name: 'Idaho',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'ID', slug: 'idaho' })",
		},
		GU: {
			name: 'Guam',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'GU', slug: 'guam' })",
			hide: 'no',
		},
		VI: {
			name: 'Virgin Islands',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'VI', slug: 'virgin-islands' })",
			hide: 'no',
		},
		PR: {
			name: 'Puerto Rico',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'PR', slug: 'puerto-rico' })",
			hide: 'no',
		},
		AS: {
			name: 'American Samoa',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'AS', slug: 'american-samoa' })",
			hide: 'no',
		},
		MP: {
			name: 'Northern Mariana Islands',
			description: 'default',
			color: 'default',
			hover_color: 'default',
			url: "javascript:clickState({ abbreviation: 'MP', slug: 'northern-mariana-islands' })",
			hide: 'no',
		},
	},
	locations: {
		// '0': {
		// 	name: 'New York',
		// 	lat: 40.71,
		// 	lng: -74,
		// 	description: 'default',
		// 	color: 'default',
		// 	url: 'default',
		// 	type: 'default',
		// 	size: 'default',
		// },
		// '1': {
		// 	name: 'Anchorage',
		// 	lat: 61.2180556,
		// 	lng: -149.9002778,
		// 	color: 'default',
		// 	type: 'circle',
		// },
	},
	labels: {
		NH: {
			parent_id: 'NH',
			x: '932',
			y: '183',
			pill: 'yes',
			width: 45,
			display: 'all',
		},
		VT: {
			parent_id: 'VT',
			x: '883',
			y: '243',
			pill: 'yes',
			width: 45,
			display: 'all',
		},
		RI: {
			parent_id: 'RI',
			x: '932',
			y: '273',
			pill: 'yes',
			width: 45,
			display: 'all',
		},
		NJ: {
			parent_id: 'NJ',
			x: '883',
			y: '273',
			pill: 'yes',
			width: 45,
			display: 'all',
		},
		DE: {
			parent_id: 'DE',
			x: '883',
			y: '303',
			pill: 'yes',
			width: 45,
			display: 'all',
		},
		MD: {
			parent_id: 'MD',
			x: '932',
			y: '303',
			pill: 'yes',
			width: 45,
			display: 'all',
		},
		DC: {
			parent_id: 'DC',
			x: '884',
			y: '332',
			pill: 'yes',
			width: 45,
			display: 'all',
		},
		MA: {
			parent_id: 'MA',
			x: '932',
			y: '213',
			pill: 'yes',
			width: 45,
			display: 'all',
		},
		CT: {
			parent_id: 'CT',
			x: '932',
			y: '243',
			pill: 'yes',
			width: 45,
			display: 'all',
		},
		HI: {
			parent_id: 'HI',
			x: 305,
			y: 565,
			pill: 'yes',
		},
		AK: {
			parent_id: 'AK',
			x: '113',
			y: '495',
		},
		FL: {
			parent_id: 'FL',
			x: '773',
			y: '510',
		},
		ME: {
			parent_id: 'ME',
			x: '893',
			y: '85',
		},
		NY: {
			parent_id: 'NY',
			x: '815',
			y: '158',
		},
		PA: {
			parent_id: 'PA',
			x: '786',
			y: '210',
		},
		VA: {
			parent_id: 'VA',
			x: '790',
			y: '282',
		},
		WV: {
			parent_id: 'WV',
			x: '744',
			y: '270',
		},
		OH: {
			parent_id: 'OH',
			x: '700',
			y: '240',
		},
		IN: {
			parent_id: 'IN',
			x: '650',
			y: '250',
		},
		IL: {
			parent_id: 'IL',
			x: '600',
			y: '250',
		},
		WI: {
			parent_id: 'WI',
			x: '575',
			y: '155',
		},
		NC: {
			parent_id: 'NC',
			x: '784',
			y: '326',
		},
		TN: {
			parent_id: 'TN',
			x: '655',
			y: '340',
		},
		AR: {
			parent_id: 'AR',
			x: '548',
			y: '368',
		},
		MO: {
			parent_id: 'MO',
			x: '548',
			y: '293',
		},
		GA: {
			parent_id: 'GA',
			x: '718',
			y: '405',
		},
		SC: {
			parent_id: 'SC',
			x: '760',
			y: '371',
		},
		KY: {
			parent_id: 'KY',
			x: '680',
			y: '300',
		},
		AL: {
			parent_id: 'AL',
			x: '655',
			y: '405',
		},
		LA: {
			parent_id: 'LA',
			x: '550',
			y: '435',
		},
		MS: {
			parent_id: 'MS',
			x: '600',
			y: '405',
		},
		IA: {
			parent_id: 'IA',
			x: '525',
			y: '210',
		},
		MN: {
			parent_id: 'MN',
			x: '506',
			y: '124',
		},
		OK: {
			parent_id: 'OK',
			x: '460',
			y: '360',
		},
		TX: {
			parent_id: 'TX',
			x: '425',
			y: '435',
		},
		NM: {
			parent_id: 'NM',
			x: '305',
			y: '365',
		},
		KS: {
			parent_id: 'KS',
			x: '445',
			y: '290',
		},
		NE: {
			parent_id: 'NE',
			x: '420',
			y: '225',
		},
		SD: {
			parent_id: 'SD',
			x: '413',
			y: '160',
		},
		ND: {
			parent_id: 'ND',
			x: '416',
			y: '96',
		},
		WY: {
			parent_id: 'WY',
			x: '300',
			y: '180',
		},
		MT: {
			parent_id: 'MT',
			x: '280',
			y: '95',
		},
		CO: {
			parent_id: 'CO',
			x: '320',
			y: '275',
		},
		UT: {
			parent_id: 'UT',
			x: '223',
			y: '260',
		},
		AZ: {
			parent_id: 'AZ',
			x: '205',
			y: '360',
		},
		NV: {
			parent_id: 'NV',
			x: '140',
			y: '235',
		},
		OR: {
			parent_id: 'OR',
			x: '100',
			y: '120',
		},
		WA: {
			parent_id: 'WA',
			x: '130',
			y: '55',
		},
		ID: {
			parent_id: 'ID',
			x: '200',
			y: '150',
		},
		CA: {
			parent_id: 'CA',
			x: '79',
			y: '285',
		},
		MI: {
			parent_id: 'MI',
			x: '663',
			y: '185',
		},
		PR: {
			parent_id: 'PR',
			x: '620',
			y: '545',
		},
		GU: {
			parent_id: 'GU',
			x: '550',
			y: '540',
		},
		VI: {
			parent_id: 'VI',
			x: '680',
			y: '519',
		},
		MP: {
			parent_id: 'MP',
			x: '570',
			y: '575',
		},
		AS: {
			parent_id: 'AS',
			x: '665',
			y: '580',
		},
	},
	regions: {
		'new-england': {
			name: 'New England',
			states: ['ME', 'NH', 'VT', 'MA', 'CT', 'RI'],
			url: "javascript:clickRegion('new-england')",
		},
		'mid-atlantic': {
			name: 'Mid-Atlantic',
			states: ['NY', 'NJ', 'PA'],
			url: "javascript:clickRegion('mid-atlantic')",
		},
		midwest: {
			name: 'Midwest',
			states: ['IL', 'IN', 'IA', 'KS', 'MI', 'MN', 'MO', 'NE', 'ND', 'OH', 'SD', 'WI'],
			url: "javascript:clickRegion('midwest')",
		},
		south: {
			name: 'South',
			states: [
				'AL',
				'AR',
				'DC',
				'DE',
				'FL',
				'GA',
				'KY',
				'LA',
				'MD',
				'MS',
				'NC',
				'OK',
				'SC',
				'TN',
				'TX',
				'VA',
				'WV',
			],
			url: "javascript:clickRegion('south')",
		},
		west: {
			name: 'West',
			states: ['CO', 'NM', 'AZ', 'AK', 'HI', 'ID', 'MT', 'NV', 'UT', 'WY', 'WA', 'OR', 'CA'],
			url: "javascript:clickRegion('west')",
		},
		'us-territories': {
			name: 'US Territories',
			states: ['GU', 'VI', 'PR', 'AS', 'MP'],
			url: "javascript:clickRegion('us-territories')",
		},
	},
};
